# Generated by Codex on 2026-04-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.SmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("comment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="workshop.comment")),
                ("voter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comment_votes", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "workshop_comment_vote",
                "unique_together": {("comment", "voter")},
            },
        ),
    ]
