# Generated by Django 5.2.12 on 2026-04-13 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('skill_requirements', models.TextField(blank=True)),
                ('bounty_type', models.CharField(choices=[('SKILL_CUSTOM', 'Skill 定制'), ('DATA_PROCESSING', '数据处理'), ('CONTENT_CREATION', '内容创作'), ('BUG_FIX', '问题修复'), ('GENERAL', '通用任务')], max_length=30)),
                ('max_applicants', models.PositiveIntegerField(default=1)),
                ('workload_estimate', models.CharField(blank=True, choices=[('ONE_TO_TWO_HOURS', '1~2小时'), ('HALF_DAY', '半天'), ('ONE_DAY', '1天'), ('TWO_TO_THREE_DAYS', '2~3天'), ('ONE_WEEK_PLUS', '1周以上')], max_length=30)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('OPEN', '开放'), ('IN_PROGRESS', '进行中'), ('DELIVERED', '已交付'), ('IN_REVIEW', '审核中'), ('REVISION', '需修改'), ('COMPLETED', '已完成'), ('DISPUTED', '争议中'), ('ARBITRATING', '仲裁中'), ('CANCELLED', '已取消')], default='OPEN', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('revision_count', models.IntegerField(default=0)),
                ('is_cold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bounties_bounty',
            },
        ),
        migrations.CreateModel(
            name='Arbitration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_statement', models.TextField(blank=True)),
                ('hunter_statement', models.TextField(blank=True)),
                ('result', models.CharField(blank=True, choices=[('HUNTER_WIN', '接单者胜'), ('CREATOR_WIN', '发布者胜'), ('PARTIAL', '部分完成')], max_length=20)),
                ('hunter_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('appeal_fee_paid', models.BooleanField(default=False)),
                ('admin_final_result', models.CharField(blank=True, max_length=20)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to=settings.AUTH_USER_MODEL)),
                ('arbitrators', models.ManyToManyField(blank=True, related_name='arbitration_cases', to=settings.AUTH_USER_MODEL)),
                ('bounty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arbitration', to='bounties.bounty')),
            ],
            options={
                'db_table': 'bounties_arbitration',
            },
        ),
        migrations.CreateModel(
            name='BountyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.TextField()),
                ('estimated_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_applications', to=settings.AUTH_USER_MODEL)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='bounties.bounty')),
            ],
            options={
                'db_table': 'bounties_bounty_application',
                'unique_together': {('bounty', 'applicant')},
            },
        ),
        migrations.AddField(
            model_name='bounty',
            name='accepted_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_bounty', to='bounties.bountyapplication'),
        ),
        migrations.CreateModel(
            name='BountyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_comments', to=settings.AUTH_USER_MODEL)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bounties.bounty')),
            ],
            options={
                'db_table': 'bounties_bounty_comment',
            },
        ),
        migrations.CreateModel(
            name='BountyDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('attachments', models.JSONField(default=list)),
                ('revision_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='bounties.bounty')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bounties_bounty_deliverable',
            },
        ),
        migrations.CreateModel(
            name='BountyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_rating', models.IntegerField()),
                ('communication_rating', models.IntegerField()),
                ('responsiveness_rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bounties.bounty')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bounties_bounty_review',
            },
        ),
        migrations.CreateModel(
            name='ArbitrationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('HUNTER_WIN', '接单者胜'), ('CREATOR_WIN', '发布者胜'), ('PARTIAL', '部分完成')], max_length=20)),
                ('hunter_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arbitration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='bounties.arbitration')),
                ('arbitrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitration_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bounties_arbitration_vote',
                'unique_together': {('arbitration', 'arbitrator')},
            },
        ),
        migrations.AddIndex(
            model_name='bounty',
            index=models.Index(fields=['status', 'created_at'], name='bounties_bo_status_1fd076_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bountyreview',
            unique_together={('bounty', 'reviewer', 'reviewee')},
        ),
    ]
