# Generated by Codex on 2026-04-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bounties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BountyReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quality_rating", models.IntegerField()),
                ("communication_rating", models.IntegerField()),
                ("responsiveness_rating", models.IntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bounty", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="bounties.bounty")),
                ("reviewee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bounty_reviews_received", to=settings.AUTH_USER_MODEL)),
                ("reviewer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bounty_reviews_written", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "bounties_bounty_review",
                "unique_together": {("bounty", "reviewer", "reviewee")},
            },
        ),
    ]
