# Generated by Codex on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bounties", "0002_bountyreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="attachments",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="bounty",
            name="max_applicants",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="bounty",
            name="skill_requirements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bounty",
            name="workload_estimate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ONE_TO_TWO_HOURS", "1~2小时"),
                    ("HALF_DAY", "半天"),
                    ("ONE_DAY", "1天"),
                    ("TWO_TO_THREE_DAYS", "2~3天"),
                    ("ONE_WEEK_PLUS", "1周以上"),
                ],
                max_length=30,
            ),
        ),
    ]
