# Generated by Django 5.2.12 on 2026-04-18 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0003_bounty_publish_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bountyreview',
            constraint=models.CheckConstraint(condition=models.Q(('quality_rating__gte', 1), ('quality_rating__lte', 5)), name='bounty_review_quality_range'),
        ),
        migrations.AddConstraint(
            model_name='bountyreview',
            constraint=models.CheckConstraint(condition=models.Q(('communication_rating__gte', 1), ('communication_rating__lte', 5)), name='bounty_review_communication_range'),
        ),
        migrations.AddConstraint(
            model_name='bountyreview',
            constraint=models.CheckConstraint(condition=models.Q(('responsiveness_rating__gte', 1), ('responsiveness_rating__lte', 5)), name='bounty_review_responsiveness_range'),
        ),
    ]
