# Generated by Django 5.2.12 on 2026-04-13 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamelUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('role', models.IntegerField(default=1)),
                ('quota', models.IntegerField(default=0)),
                ('used_quota', models.IntegerField(default=0)),
                ('credit_score', models.IntegerField(default=0)),
                ('community_level', models.CharField(default='SEED', max_length=20)),
                ('aff_code', models.CharField(blank=True, max_length=32)),
                ('inviter_id', models.IntegerField(blank=True, null=True)),
                ('group', models.CharField(default='default', max_length=64)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('first_deposit_rewarded', models.BooleanField(default=False)),
                ('registration_ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('registration_device_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invitation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_invitation',
            },
        ),
        migrations.CreateModel(
            name='CommunityProfile',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='community_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True)),
                ('frozen_balance', models.IntegerField(default=0)),
                ('bounty_freeze_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_profiles',
            },
        ),
    ]
