# Generated by Django 5.2.12 on 2026-04-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_email_uniqueness_and_manager'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='user_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('frozen_balance__gte', 0)), name='user_frozen_balance_non_negative'),
        ),
    ]
