# Generated by Django 6.0.3 on 2026-04-04 16:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('system_prompt', models.TextField()),
                ('user_prompt_template', models.TextField(blank=True)),
                ('output_format', models.CharField(choices=[('text', '文本'), ('json', 'JSON'), ('markdown', 'Markdown'), ('code', '代码')], default='text', max_length=20)),
                ('example_input', models.TextField(blank=True)),
                ('example_output', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('CODE_DEV', '代码开发'), ('WRITING', '文案写作'), ('DATA_ANALYTICS', '数据分析'), ('ACADEMIC', '学术研究'), ('TRANSLATION', '翻译本地化'), ('CREATIVE', '创意设计'), ('AGENT', 'Agent 工具'), ('PRODUCTIVITY', '办公效率'), ('MISC', '其他')], max_length=30)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=10)),
                ('pricing_model', models.CharField(choices=[('FREE', '免费'), ('PER_USE', '按次付费')], default='FREE', max_length=10)),
                ('price_per_use', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_REVIEW', '待审核'), ('APPROVED', '已上架'), ('REJECTED', '已拒绝'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('current_version', models.IntegerField(default=1)),
                ('total_calls', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skills_skill',
            },
        ),
        migrations.CreateModel(
            name='SkillCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_version', models.IntegerField()),
                ('input_text', models.TextField()),
                ('output_text', models.TextField(blank=True)),
                ('amount_charged', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_calls', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='skills.skill')),
            ],
            options={
                'db_table': 'skills_skill_call',
            },
        ),
        migrations.CreateModel(
            name='SkillReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_reviews', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='skills.skill')),
            ],
            options={
                'db_table': 'skills_skill_review',
            },
        ),
        migrations.CreateModel(
            name='SkillVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('system_prompt', models.TextField()),
                ('user_prompt_template', models.TextField(blank=True)),
                ('change_note', models.CharField(blank=True, max_length=200)),
                ('is_major', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='skills.skill')),
            ],
            options={
                'db_table': 'skills_skill_version',
            },
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['status', 'category'], name='skills_skil_status_41e488_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['creator', 'status'], name='skills_skil_creator_3b2d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='skillcall',
            index=models.Index(fields=['skill', 'created_at'], name='skills_skil_skill_i_a91847_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skillreview',
            unique_together={('skill', 'reviewer')},
        ),
        migrations.AlterUniqueTogether(
            name='skillversion',
            unique_together={('skill', 'version')},
        ),
    ]
