# Generated by Django 5.2.12 on 2026-04-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='current_version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
    ]
