# Generated by Codex on 2026-04-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillUsagePreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("locked_version", models.IntegerField(blank=True, null=True)),
                ("auto_follow_latest", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("skill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="usage_preferences", to="skills.skill")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="skill_usage_preferences", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "skills_skill_usage_preference",
                "unique_together": {("skill", "user")},
            },
        ),
    ]
