# Generated by Django 5.2.12 on 2026-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_add_scan_result_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='current_version',
            field=models.CharField(default='1.0.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='skillcall',
            name='skill_version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skillusagepreference',
            name='locked_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='skillversion',
            name='version',
            field=models.CharField(max_length=50),
        ),
    ]
