# Generated by Django 5.2.12 on 2026-04-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_version_fields_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillversion',
            name='pending_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
