# Generated by Django 6.0.3 on 2026-04-04 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', '充值'), ('SKILL_PURCHASE', 'Skill 调用扣费'), ('SKILL_INCOME', 'Skill 收入'), ('BOUNTY_ESCROW', '悬赏冻结'), ('BOUNTY_RELEASE', '悬赏解冻'), ('BOUNTY_INCOME', '悬赏收入'), ('TIP_SEND', '打赏支出'), ('TIP_RECEIVE', '打赏收入'), ('PLATFORM_FEE', '平台手续费'), ('REFUND', '退款')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_transaction',
                'indexes': [models.Index(fields=['user', 'created_at'], name='payments_tr_user_id_4ab1c7_idx')],
            },
        ),
    ]
