# Generated by Django 5.2.12 on 2026-04-18 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', '充值'), ('SKILL_PURCHASE', 'Skill 购买扣费'), ('SKILL_INCOME', 'Skill 收入'), ('BOUNTY_ESCROW', '悬赏冻结'), ('BOUNTY_RELEASE', '悬赏解冻'), ('BOUNTY_INCOME', '悬赏收入'), ('TIP_SEND', '打赏支出'), ('TIP_RECEIVE', '打赏收入'), ('PLATFORM_FEE', '平台手续费'), ('REFUND', '退款')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_payment_intent', ''), _negated=True), fields=('stripe_payment_intent',), name='unique_stripe_payment_intent'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_id__startswith', 'stripe_session:')), fields=('reference_id',), name='unique_stripe_session_reference'),
        ),
    ]
