# Generated by Django 5.2.12 on 2026-04-13 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('REGISTER', '注册奖励'), ('PUBLISH_SKILL', '发布 Skill'), ('SKILL_CALLED', 'Skill 被调用'), ('PUBLISH_ARTICLE', '发布文章'), ('ARTICLE_FEATURED', '文章加精'), ('BOUNTY_COMPLETED', '完成悬赏'), ('TIP_GIVEN', '打赏他人'), ('ARBITRATION_SERVED', '参与仲裁'), ('INVITE_REGISTERED', '邀请注册'), ('BOUNTY_TIMEOUT', '悬赏超时惩罚'), ('BOUNTY_FREEZE', '悬赏板冻结'), ('ADMIN_ADJUST', '管理员调整')], max_length=30)),
                ('amount', models.IntegerField()),
                ('score_before', models.IntegerField()),
                ('score_after', models.IntegerField()),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credits_credit_log',
                'indexes': [models.Index(fields=['user', 'created_at'], name='credits_cre_user_id_ed0e8e_idx')],
            },
        ),
    ]
